CREATE TABLE `students` (
	`id` varchar(36) NOT NULL,
	`company_id` varchar(36),
	`name` varchar(100) NOT NULL,
	`surname` varchar(100) NOT NULL,
	`email` varchar(255) NOT NULL,
	`course` varchar(255),
	`nationality` varchar(100),
	`academic_year` varchar(20),
	`phone` varchar(50),
	`mobile` varchar(50),
	`country` varchar(100),
	`country_of_residence` varchar(100),
	`full_address` varchar(500),
	`date_of_birth` varchar(20),
	`gender` varchar(50),
	`marital_status` varchar(50),
	`passport_number` varchar(50),
	`issue_place` varchar(100),
	`issue_country` varchar(100),
	`issue_date` varchar(20),
	`expiry_date` varchar(20),
	`contact_name` varchar(100),
	`contact_address` varchar(500),
	`contact_phone` varchar(50),
	`contact_email` varchar(255),
	`relationship` varchar(100),
	`agency_name` varchar(255),
	`agency_email` varchar(255),
	`accept_privacy` boolean DEFAULT false,
	`created_at` timestamp DEFAULT (now()),
	CONSTRAINT `students_id` PRIMARY KEY(`id`),
	CONSTRAINT `students_email_unique` UNIQUE(`email`)
);
--> statement-breakpoint
ALTER TABLE `students` ADD CONSTRAINT `students_company_id_companies_id_fk` FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON DELETE no action ON UPDATE no action;